# 实训1 创建数组并进行运算

In [1]:
import numpy as np

#第一步
First = np.arange(0,1,0.01)#生成均匀数组
print("数值范围为0-1，间隔为0.01的数组：\n",First)


数值范围为0-1，间隔为0.01的数组：
 [0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]


In [2]:
#第二步
Second = np.random.randn(1,100)#生成正态分布随机数
print("100个服从正态分布的随机数为:",Second)


100个服从正态分布的随机数为: [[ 0.86016174 -0.55917985  0.81139396  0.89337423 -0.78930276 -0.01634128
   1.19135569 -0.47163799  0.1395197  -0.33143748  0.39569891 -0.8440782
  -0.37178217  1.40221725 -0.3654605   1.0888198   0.29681296 -1.50489883
  -0.06577541  0.28420206  0.19674832  1.11930532  0.2650266  -0.53548265
  -1.81092187  0.93704444  0.7174273   2.35421807  0.73596861 -0.77304688
   0.44380023  0.3623491   0.4285507   0.05348517  1.2587505   1.33923687
   1.40908305  1.13854134 -0.91312313  0.69097013  0.5135805   2.36548443
  -0.17535938  2.14723475  0.78002569  0.3978482  -0.43035852  0.15330601
  -1.01817802  0.31037961  1.49286689  1.6515784   0.22612388  1.3607165
   0.3745597  -0.73737    -1.02018699 -0.95905788  0.96148505 -1.2742836
  -0.10284718 -1.52609145 -1.16405574  2.07823966  0.53336232 -1.19613077
  -0.60268148  0.68762159  1.13600379  1.17981009  0.98751792 -0.04342905
   0.33531878  0.39616158  0.99797419 -0.26364816  0.47828402  1.61466185
  -1.06747653 -0.5517822

In [3]:
#第三步
Second.resize(100)
#四则运算
HeRes = Second+First
print("两数组和的结果",HeRes)
CharRes = Second-First
print("两数组差的结果",CharRes)
JiRes = Second*First
print("两数组积的结果",JiRes)
ShangRes = First/Second
print("两数组商的结果",ShangRes)


两数组和的结果 [ 8.60161742e-01 -5.49179845e-01  8.31393958e-01  9.23374226e-01
 -7.49302757e-01  3.36587232e-02  1.25135569e+00 -4.01637992e-01
  2.19519696e-01 -2.41437478e-01  4.95698907e-01 -7.34078202e-01
 -2.51782170e-01  1.53221725e+00 -2.25460501e-01  1.23881980e+00
  4.56812956e-01 -1.33489883e+00  1.14224592e-01  4.74202057e-01
  3.96748322e-01  1.32930532e+00  4.85026600e-01 -3.05482648e-01
 -1.57092187e+00  1.18704444e+00  9.77427295e-01  2.62421807e+00
  1.01596861e+00 -4.83046876e-01  7.43800227e-01  6.72349101e-01
  7.48550702e-01  3.83485168e-01  1.59875050e+00  1.68923687e+00
  1.76908305e+00  1.50854134e+00 -5.33123130e-01  1.08097013e+00
  9.13580505e-01  2.77548443e+00  2.44640618e-01  2.57723475e+00
  1.22002569e+00  8.47848201e-01  2.96414806e-02  6.23306014e-01
 -5.38178023e-01  8.00379614e-01  1.99286689e+00  2.16157840e+00
  7.46123878e-01  1.89071650e+00  9.14559702e-01 -1.87370003e-01
 -4.60186986e-01 -3.89057875e-01  1.54148505e+00 -6.84283603e-01
  4.97152824e-01 

In [4]:
#第四步
#简单数学统计
print("最大值",np.max(Second))
print("最小值",np.min(Second))
print("所有元素和",np.sum(Second))
print("所有元素积",np.prod(Second))
print("标准差",np.std(Second))
print("方差",np.var(Second))
print("平均值",np.mean(Second))
print("中位数",np.median(Second))


#去重
res = np.unique(Second)
#print("去重后的数组",res)

#重复
res = Second.repeat(2)
#print("重复后的数组",res)
#排序方法
tmp = Second
Second.sort()
#print('sort排序后的数组',Second)

Second = tmp
temp = Second.argsort()
#print('argsort排序后的数组',temp)

res = np.lexsort((First,Second))
res = list(zip(First[res],Second[res]))
print('lexsort排序后的数组',res)



最大值 2.365484432233044
最小值 -2.326963675001856
所有元素和 15.788147709186658
所有元素积 -1.0957241704089125e-23
标准差 0.9852985184883591
方差 0.9708131705353554
平均值 0.1578814770918666
中位数 0.2746143283764399
lexsort排序后的数组 [(0.0, -2.326963675001856), (0.01, -2.1456772639552177), (0.02, -1.8109218698263276), (0.03, -1.5260914549965392), (0.04, -1.5238090181931545), (0.05, -1.5048988275496407), (0.06, -1.449650498534995), (0.07, -1.2742836033588938), (0.08, -1.196130765979224), (0.09, -1.164055737490963), (0.1, -1.067476530582851), (0.11, -1.020186985903667), (0.12, -1.0181780234708946), (0.13, -0.9590578753020996), (0.14, -0.9131231303762993), (0.15, -0.9122254879715546), (0.16, -0.8598332374225809), (0.17, -0.8440782016715468), (0.18, -0.7893027574817693), (0.19, -0.7730468755718369), (0.2, -0.7373700032228725), (0.21, -0.6946579134658861), (0.22, -0.6026814770238388), (0.23, -0.5658996577283293), (0.24, -0.5642442138039219), (0.25, -0.559179845105321), (0.26, -0.5517822295438973), (0.27, -0.53548264768

# 实训2 国际象棋棋盘

In [6]:
chessboard = np.zeros((8,8))

for i in range(8):
    if(i%2==0):
        chessboard[i] = 1
    else:
        chessboard[:,i] = 1
print("棋盘")
print(chessboard)

棋盘
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
